version: '3'

services:
  mongo:
    image: mongo:5.0.11
    container_name: mongo
    volumes:
      - guild-mongovolume:/data/db
      - guild-mongoconfig:/data/configdb

  go-app:
    build: .
    image: localhost/go-image:3
    container_name: go-app
    ports:
      - 8080:8080

volumes:
  guild-mongovolume:
    name: guild-mongovolume
  guild-mongoconfig:
    name: guild-mongoconfig

networks:
  default:
    name: go-guild